version: '3.8'
services:
    web:
        build: .
        entrypoint: ["/bin/sh","-c"]
        command:
            - |
               python quotes_daemon.py &
               sleep 2
               python main.py &
               locust -f locustfile.py --host=http://localhost:8000 --users 500 --spawn-rate 50 --run-time 30s --headless --only-summary > log/locust_load_test.log 2>&1
               cat log/locust_load_test.log
        ports:
            - 8000:8000
